name: Build binary

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip
    - name: Build
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload static binaries
      uses: actions/upload-artifact@v3
      with:
        name: magic-mount-static
        path: native/libs/static
    - name: Upload dynamic binaries
      uses: actions/upload-artifact@v3
      with:
        name: magic-mount-dynamic
        path: native/libs/dynamic
