name: Build binary

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: SetupNDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
    - name: Build
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: magic-mount-release
        path: native/libs

    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          out/magic-mount-release.zip
